#! /bin/sh

# home
#bspc monitor -d I II III IV V VI VII VIII IX X
#feh --bg-scale Pictures/Wallpapers/color15.png
#synclient tapbutton1=1
# work
xrandr --output LVDS1 --off
bspc monitor VGA1 -d I II III IV V VI VII VIII IX X
bspc desktop I -f
feh --bg-scale Pictures/Wallpapers/triangle_form_light_dark_88543_1920x1200.jpg
# presentation
#xrandr --output LVDS1 --off
#bspc monitor VGA1 -d I II III IV V VI VII VIII IX X
#bspc desktop I -f
#feh --bg-scale Pictures/Wallpapers/triangle_form_light_dark_88543_1920x1200.jpg

bspc config border_width        1
bspc config window_gap          10
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
wmname LG3D

#bspc rule -a urxvt desktop=I
bspc rule -a Atom desktop=II
bspc rule -a chromium desktop=III # state=floating
#bspc rule -a sun-awt-X11-XFramePeer state=floating
#bspc rule -a XMathematica desktop=II state=floating
bspc rule -a feh state=floating
bspc rule -a display state=floating
bspc rule -a skype state=floating
bspc rule -a Wine state=floating
bspc rule -a Image state=floating
#bspc rule -a jetbrains-pycharm desktop=^2 state=floating
bspc rule -a rstudio desktop=II state=floating
bspc rule -a mpv desktop=V state=floating
